# Generated by Django 4.1.13 on 2023-11-17 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_oferta', models.CharField(max_length=20)),
                ('descripcion_oferta', models.CharField(max_length=500)),
                ('empresa_oferta', models.CharField(max_length=20)),
                ('fecha_oferta', models.DateField()),
            ],
        ),
    ]
