# Generated by Django 4.1.13 on 2023-11-24 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oferta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='nombre_oferta',
            field=models.CharField(default='oferta', max_length=50),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='fecha_oferta',
            field=models.CharField(max_length=8),
        ),
    ]
