# Generated by Django 4.1.13 on 2023-11-24 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oferta', '0002_oferta_nombre_oferta_alter_oferta_fecha_oferta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='fecha_oferta',
            field=models.DateTimeField(),
        ),
    ]
