# Generated by Django 4.1.13 on 2023-11-24 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario', models.CharField(max_length=20)),
                ('correo_usuario', models.CharField(max_length=100)),
                ('telefono_usuario', models.IntegerField()),
                ('edad_usuario', models.IntegerField()),
                ('nivel_educacion', models.CharField(max_length=45)),
                ('genero_usuario', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='AdministradorMag',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usuario.usuario')),
                ('id_adminMag', models.CharField(max_length=20)),
            ],
            bases=('usuario.usuario',),
        ),
        migrations.CreateModel(
            name='AnalistaPropuesta',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usuario.usuario')),
                ('id_analista', models.CharField(max_length=20)),
                ('empresa_analista', models.CharField(max_length=20)),
            ],
            bases=('usuario.usuario',),
        ),
        migrations.CreateModel(
            name='Aplicante',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usuario.usuario')),
                ('nombre_aplicante', models.CharField(max_length=100)),
            ],
            bases=('usuario.usuario',),
        ),
    ]
