# Generated by Django 4.1.13 on 2023-11-06 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_parrafo_palabras_subrayadas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_propuesta', models.CharField(max_length=15)),
                ('nombre_empresa', models.CharField(max_length=15)),
                ('descripcion_propuesta', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario', models.CharField(max_length=15)),
                ('nombre_usuario', models.IntegerField()),
            ],
        ),
    ]
