# Generated by Django 4.1.13 on 2023-11-24 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_empresa', models.CharField(max_length=20)),
                ('nombre_empresa', models.CharField(max_length=50)),
                ('num_ofertas', models.IntegerField()),
            ],
        ),
    ]
